runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3.5.2
    - shell: cmd
      run: echo Cloning app
    - uses: actions/checkout@v3.5.2
      with:
        repository: 'mtararujs/python-greetings'
        path: 'app'
    - working-directory: 'app'
      shell: cmd
      run:
        echo Installing dependencies
        pip install -r requirements.txt