runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3.5.2
    - run: echo Cloning app
      shell: cmd
    - uses: actions/checkout@v3.5.2
      with:
        repository: 'mtararujs/python-greetings'
        path: 'app'
    - run: echo Installing dependencies
      shell: cmd
    - working-directory: 'app'
      shell: cmd
      run: pip install -r requirements.txt